### ISSUE TITLE
to_markdown isn't outputting all the pages but get_text is

### ISSUE THREAD

**Issue by martyphee** [pymupdf/RAG#162]
### Description of the bug

I'm trying to output a PDF as markdown but not all the pages are extracted. It knows it's there and it adds an page break for it but none of the text is output. This doesn't happen with all the PDF's just a few so far. 

### How to reproduce the bug

This is the code I'm using to extract the text.

Markdown extraction

```python
md_text = pymupdf4llm.to_markdown(os.path.join(pdf_path, file))
pathlib.Path(os.path.join(output_path, f"{file.split('.')[0]}.md")).write_bytes(md_text.encode())
```

Text extraction
```python
with pymupdf.open(fname) as doc:  # open document
    text = chr(12).join([page.get_text() for page in doc])
       
output_file = os.path.join(output_path, f"{file.split('.')[0]}.txt")
pathlib.Path(output_file).write_bytes(text.encode())
```

This is a publicly available document from the FDA website.

[K240016.pdf](https://github.com/user-attachments/files/17268670/K240016.pdf)
[K240016.md](https://github.com/user-attachments/files/17268671/K240016.md)
[K240016.txt](https://github.com/user-attachments/files/17268672/K240016.txt)

### PyMuPDF version

1.24.11

### Operating system

MacOS

### Python version

3.12

**Comment by JorjMcKie** [comment]
The problem here is that this document contains too many confusing vector graphics elements, which are actually unimportant for the contained text.
The extraction algorithm however tries to make sense out of them and gets lost on the last page.
The only way out in cases like this document is **_ignoring_** the vector graphics altogether - potentially except those that form table grids.
Here is an example how the markdown algorithm can be adjusted to so it extracts all text on all pages.
```python
import pymupdf
import pymupdf4llm
import sys, pathlib

filename = sys.argv[1]
doc = pymupdf.open(filename)
md = ""

# do header identification once only - instead for each page
hdr_info = pymupdf4llm.IdentifyHeaders(doc)

# loop through pages and remove all vector graphics before text extraction
for page in doc:
    # remove vector graphics, maintain images and text
    page.add_redact_annot(page.rect)
    page.apply_redactions(
        images=pymupdf.PDF_REDACT_IMAGE_NONE,
        graphics=pymupdf.PDF_REDACT_LINE_ART_REMOVE_IF_TOUCHED,
        text=pymupdf.PDF_REDACT_TEXT_NONE,
    )
    md += pymupdf4llm.to_markdown(
        doc,
        pages=[page.number],
        margins=0,
        hdr_info=hdr_info,
        show_progress=False,
    )
pathlib.Path(doc.name + ".md").write_bytes(md.encode())
```

There is no way to enhance the extraction logic to cope with situations like this one.
So the only thing we can offer is an option which does the equivalent of the above graphics removal.
[K240016.pdf.md](https://github.com/user-attachments/files/17268889/K240016.pdf.md)

**Comment by martyphee** [comment]
Thank you for the help. I'll give that a try.

**Comment by tophee** [comment]
Did you find a solution for this?

I am getting only line breaks and dashes from a document when using `pymupdf4llm` (also when using [the code above](https://github.com/pymupdf/RAG/issues/162#issuecomment-2395379088)). The output md looks like this:
````
-----

-----

-----

-----

````
and so on.

When I use `pymupdf`, the same document is rendered just fine.

With the code below, I even get it in markdown:
```python
import pymupdf
import pathlib

# Open the PDF
doc = pymupdf.open("input.pdf")
md_text = ""

# Iterate through pages and extract text
for page_number, page in enumerate(doc, start=1):
    text = page.get_text()  
    md_text += f"\n\n# Page {page_number}\n\n{text}" 

# Save the Markdown text to a file
output_path = pathlib.Path("output.md")
output_path.write_text(md_text, encoding="utf-8")
print(f"Markdown saved to {output_path}")
```

**Comment by JorjMcKie** [comment]
No.
What you can do now is completely **_ignoring_** images and or vector graphics with the respective new parameters.

**Comment by tophee** [comment]
Interesting. But it's not working for me (still getting the same dashes and empty lines as above). Am I doing something wrong? Here is my code:

````
import pymupdf4llm
import pathlib

md_text = pymupdf4llm.to_markdown("input.pdf", ignore_images=True, ignore_graphics=True)

pathlib.Path("output.md").write_bytes(md_text.encode())
````

**Comment by JorjMcKie** [comment]
@tophee Please provide your problem file / page.
When you say "renders fine" I hope you mean that standard text extraction (PyMuPDF) does work? ... As opposed to "looks good in a PDF viewer"?

**Comment by tophee** [comment]
Yes, I mean it renders fine with PyMuPDF. Here is the input file: [input.pdf](https://github.com/user-attachments/files/20014496/input.pdf)

Note that my aim is not to solve this particular file but rather to understand which toll I should routinely use to produce text (or md) versions of the pdfs I use. Not all of them will be problematic, but this one happens to be the first I tried.

**Comment by tophee** [comment]
> The answer is that - believe it or not! - is **invisible**.

You mean the text is invisible? All of the text?

> What you see is an image, probably scanned.

Isn't it a common thing in scanned and OCR:ed documents that the actual text is hidden behind the image. Or are you saying that even if the scanned image was removed, the text would be invisible? - In that case it looks like whoever scanned the image (or set the parameters for the scanning) was a bit overambitious thinking something like "Oh, we're keeping the image of the text, so we can make the text invisible." I wish they instead made other parts of the text invisible.

> But if your PDFs are of that type usually, you do not need pymupdf4llm anyway.

That's what I'm trying to figure out. The reason I wanted to try pymupdf4llm is that (I think) it can detect sematic structure, i.e. render headings as markdown headings. Is that correct?

**Comment by JorjMcKie** [comment]
> Or are you saying that even if the scanned image was removed, the text would be invisible?

Yes, exactly that. But that is normal for OCR: either put text underneath the image, correctly positioned such that marking / selecting it coincides with the visible stuff inside the image, or put it above the image with alpha = 0 (transparency 100%).

> That's what I'm trying to figure out. The reason I wanted to try pymupdf4llm is that (I think) it can detect sematic structure, i.e. render headings as markdown headings. Is that correct?

Correct. So you are in the unfortunate situation that you want to use pymupdf4llm features, but pymupdf4llm takes invisibility seriously.

**Comment by JorjMcKie** [comment]
Maybe I do  need to do something here. It could be a new parameter like `ignore_visibility` or `accept_transparency` or something.

**Comment by tophee** [comment]
`ignore_invisibility` might be more intuitively understandable. Then again even that can be read as ”ignore invisible text”. So, perhaps  `ignore_transparency` is least ambiguous. Or what about a `visibility_threshold`, i.e. an alpha value above which text is considered visible. The default value would be 0, so 0 would be invisible, but if you set it to something below 0, 0 becomes visible. 

Whatever you call it, I think such a parameter makes  sense. I would design it to be used with mixed pdf documents, i.e. docs which include both visible and invisible text. For the edge case where all text is invisible, I would suggest the invidible text is automatically treated as visible. 

I’m assuming here that my document would fall into that category, but as I think about it, I’m not sure whether it would technically qualify, given that a few dashes are output on every page. But you get the idea.

My understanding is that my document is a rather unusual case and none of my other pdf docs may have this problem. I will check that asap.

If it is indeed rare, I think I would still go ahead and use pymupdf4llm on my pdfs by default and only switch to pymupdf if pymupdf4llm yields no text. I suppose I can do this programmatically but I’m not sure whether I can assume to get exactly the output [above](https://github.com/pymupdf/RAG/issues/162#issuecomment-2842145042) when there is no text or whether I need a more sophisticated test.

Thank you for looking into this. I learned a lot from what you wrote.

**Comment by JorjMcKie** [comment]
Thanks for your comments.
I think I can achieve the goal without a new parameter: PyMuPDF has a way to check if **_all text_** on the page is invisible.
If this is detected, I will assume we have an OCR-ed page and do **_not_** throw invisible text away. I have attached the Markdown output reflecting this approach.

In these experiments, the typical issues with OCR were showing up: every OCR engine builds boundary boxes around words, like for instance "area". As it cannot know the original fonts and their properties, it has to guess what it is looking at and derive things like font size from the height of the boundary box.
It cannot know (for sure) if the text is bold or italic, and it may measure the boundary box of the same word "area" somewhere else slightly differently - which will then result in a different font size.

In this example, apparent body text on page 1 has a font size of 12 (rounded), but font size 13 (rounded) on later pages. Except for the top line on page 1, no other header can be identified on later pages, etc., etc.

[input.md](https://github.com/user-attachments/files/20023361/input.md)

**Comment by tophee** [comment]
Interesting. I agree: If we can assume that OCR-ed pdfs with invisible text will always have all text invisible, then a new parameter is probably not necessary.

The output looks good to me. It did not recognize any document structure (headings), though (apart from the title). Is that the default or does it simply fail at mapping the bold lines of text onto headings, in this particular doc. Perhaps because it (or rather: the OCR) also  identified most page headers as bold?

An aside: speaking of headers and headings: I found the text on https://pypi.org/project/pymupdf4llm/ a bit confusing when it uses the word "header" for what is usually called "heading" (whereas header would usually be the sister term to footer). In this specific context (where users may well wish to not only identify headings but also headers), the confusion is a bit unfortunate. I also found it in another text but I don't remember where (blog-post?).

I have tried to find more detailed descriptions/instructions about how pymupdf4llm identifies headings (or possibly other markdown elements), but couldn't find much. In the pymupdf documentation there is a link to detecting MD with pymupdf4ll but that link just leads to a section that says you should use `pymupdf4llm.to_markdown()`. Maybe that is all there is to it? No flags? No parameters?

One parameter that might be useful (or which might even work as a built-in part of the headings-detection algorithm) is that lines that are using caps only, should be interpreted as headings. In the case of my doc, this would have revealed the basic structure of the document.
