### ISSUE TITLE
Table text without new lines

### ISSUE THREAD

**Issue by papipsycho** [pymupdf/RAG#19]
Hello, 

i'was testing this project, and i remark that we having issue with new lines inside the table.

i checked a bit and it seems came from the function to_markdown into output_table, i suggest to use .to_pandas().to_markdown() to keep the new line inside a cell.

Best

**Comment by JorjMcKie** [comment]
Sorry, don't understand what that means. Please provide examples!

**Comment by papipsycho** [comment]
@JorjMcKie 

Sorry for the delay, But here some screenshot
with to_markdown() only 
![image_2024_05_27T05_29_37_928Z](https://github.com/pymupdf/RAG/assets/20132010/f0c50beb-093c-486e-a448-a45c3956d813)


with .to_pandas().to_markdown() 
![bimage_2024_05_27T05_30_37_311Z](https://github.com/pymupdf/RAG/assets/20132010/04e9dd73-77c3-46fe-9b10-e9b9c9216707)


as you can see we loose the \n

**Comment by JorjMcKie** [comment]
We will not use `DataFrame.to_markdown()`, because it unnecessarily introduces external dependencies plus also increases execution time.
The markdown output is intended first and above all for serving LLM / RAG upstream applications with an easy to read input format with yet complete data.
Its goal is **_not_** creating nice-looking markdown versions of input documents primarily. Therefore in this context, loosing line breaks in table cells (and replacing them with spaces) is an affordable loss of appearance quality - not information content.
