### ISSUE TITLE
The package sometimes stuck for too long 

### ISSUE THREAD

**Issue by IronK77** [pymupdf/RAG#99]
So it is me again.

I have found a small issue that sometimes the processing time can be too long (>30min) for some pdfs and the work still cannot be done. I will see if I can find some examples about this issue. I have tried the limit on image processing, but there is no effect. Since it is totally fine for to skip one or two pdfs in a 2000-pdf queue, I wonder if there can be a breaker setting or I can write a breaker using other packages.

**Comment by dantetemplar** [comment]
May you provide example of such PDF?

**Comment by JorjMcKie** [comment]
This package is based on PyMuPDF as you know.
Tremendous amounts of vector graphics on pages can cause slowdowns because the `to_markdown()` method checks these objects when identifying text columns and tables.

Otherwise, time consumption is the same as in PyMuPDF itself. If you experience extraneous runtimes in spite of omitting pages with many vector graphics and using `table_strategy="lines_strict"`, then PyMuPDF itself will have the same problem with that document.
There indeed exist PDFs with an unfortunate internal structure, which cause any extractor to take long execution times.

**Comment by JorjMcKie** [comment]
Close for lack of reaction over an extended period of time.
